# Generated by Django 3.1.7 on 2021-03-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HongyiOJ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acceptedCnt',
            field=models.IntegerField(default=0),
        ),
    ]
